### ISSUE TITLE
[Bug] Quick start still referring to bootstrap@5.0.1-beta1

### ISSUE THREAD

**Issue by bram-atmire** [creativetimofficial/ct-now-ui-design-system-pro#1]
### Version
2.0.1
### Reproduction link
https://www.creative-tim.com/learning-lab/bootstrap/quick-start/now-ui-design-system
### Operating System
Mac OSX
### Device
Macbook
### Browser & Version
Chrome
### Steps to reproduce
1. Look at section "Bootstrap CDN" of the quick start docs
### What is expected?
Seeing the same bootstrap version as the one mentioned in the changelog, e.g. 5.0.2
### What is actually happening?
It shows bootstrap@5.0.1-beta1

---
### Solution
Update docs with CDN download links with Bootstrap 5.0.2

**Comment by rarestoma** [comment]
Hi @bram-atmire,

Thank you for working with our products and for pointing us these details.

I just update now the docs with the proper version of Bootstrap: https://www.creative-tim.com/learning-lab/bootstrap/quick-start/now-ui-design-system.

Best regards, 
Rares

**Comment by bram-atmire** [comment]
Awesome, thank you @rarestoma for the quick fix!!!
